$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf
#  // P̳r̳a̳s̳a̳n̳t̳h̳ R̳a̳n̳g̳a̳n̳

$GTK_THEME=Catppuccin-Mocha
$ICON_THEME = Tela-circle-dracula
$COLOR_SCHEME = prefer-dark

# Optional: The varibles above will be set automatically when the theme is loaded
# This exec commands will soon be deprecated

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.inactive_border = rgba(000000ff) rgba(000000ff) 45deg
    layout = dwindle
    resize_on_border = true
    hover_icon_on_border = true
}

group {
    col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
    col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
    col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}

decoration {
    rounding = 0
    dim_inactive = false
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1

    shadow {        
        enabled = 0
    }
    blur {
        enabled = 0
        xray = 1
    }
}

animations:enabled = 0

windowrule = opaque,class:(.*) # ensure all windows are opaque

layerrule = blur,waybar 
layerrule = blur,dunst
layerrule = blur,swaync-notification-window 
layerrule = blur,rofi
layerrule = noanim,waybar 
layerrule = noanim,swaync-notification-window 
layerrule = noanim,swww-daemon 
layerrule = noanim,rofi